services:
  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "sj26/mailcatcher"
    ports:
      - "1025:1025"
      - "1080:1080"
  database:
    container_name: "techcollors-web"
    image: "postgres:17.5-alpine3.22"
    env_file:
      - ../../.env.development
    ports:
      - "5432:5432"
